version: '3'
services:
    go:
        build:
            context: ./docker/go
        container_name: favpic
        volumes:
            - .:/go/src
        ports:
            - 8082:8082
        working_dir: /go/src/app
        tty: true
        command: fresh
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: favpicDB
        volumes:
          - db-store:/var/lib/mysql
          - ./logs:/var/log/mysql
          - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
          - MYSQL_DATABASE=${DB_NAME}
          - MYSQL_USER=${DB_USER}
          - MYSQL_PASSWORD=${DB_PASS}
          - MYSQL_ROOT_PASSWORD=${DB_PASS}
          - TZ=${TZ}
        ports:
          - ${DB_PORT}:3306
volumes:
    db-store:
